In [1]:
import numpy as np

In [ ]:
l = [1, 2, 3]
x = np.array(l)
x2 = np.array([1, 2, 3], dtype='f')
x3 = np.array([1, 2, 3], dtype=np.int16)

print( type(l), type(x) )
print( x.dtype, x2.dtype, x3.dtype )

<class 'list'> <class 'numpy.ndarray'>
int64 float32 int16


In [7]:
a=np.array([1,2,3])
print (a, a.ndim)

a = np.array([[1, 2], [3, 4]])
print (a, a.ndim)

[1 2 3] 1
[[1 2]
 [3 4]] 2


In [ ]:
a=np.array([1, 2, 3, 4, 5])
print (a, a.ndim)

a=np.array([1, 2, 3, 4, 5], ndmin=2)
print (a, a.ndim)


[1 2 3 4 5] 1
[[1 2 3 4 5 6]] 2


In [13]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print (a.shape) 

a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a) 
print(a.shape) 

a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)
print(b.shape, a.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2) (2, 3)


In [ ]:
# a = np.array(range(24))
a = np.arange(24) # np.arange : 0 ~ 23까지 정수로 ndarray 만들기
print(a.ndim)
b = a.reshape(2,4,3)
print(b.ndim)
print(b)


1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [16]:
x = np.empty([3,2])
print(x)

x = np.zeros((3,2))
print(x)

x = np.ones([3,2])
print(x)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
x = np.arange(10,21,2)
print (x)

[10 12 14 16 18 20]


In [20]:
x = np.linspace(1,2,5, retstep = True)
print (x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [24]:
a = np.arange(10)
b1 = a[2:7]
b2 = a[2:7:2]
print(a)
print(b1)
print(b2)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [26]:
a = np.arange(10)
b = a[5]
print(a)
print (b)

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
a = np.arange(24)
a = a.reshape((4,6))
b = a.tolist() # ndarray -> list 변환

print(a)
b

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [30]:
print( a[1:] )
print( b[1:] )

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


In [ ]:
# 0행과 2행 데이터 조회
print(a[ [0, 2] ]) # 인덱싱을 리스트, 튜플, ndarray 등으로 수행
print([b[0], b[2]])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[0, 1, 2, 3, 4, 5], [12, 13, 14, 15, 16, 17]]


In [37]:
# 3열 데이터 조회
print( a[:,3] ) # ndarray의 2차원 인덱싱, 슬라이싱 -> ar[row-indexing, col-indexing], ar[row-slicing, col-slicing]
print( [ v[3] for v in b ] )


[ 3  9 15 21]
[3, 9, 15, 21]


In [38]:
print( a[:, [2, 5]]) # 모든 행의 2열, 5열 데이터 조회

[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]


In [39]:
print(a[[1, 3], :]) # 1, 3행의 모든 열 데이터 조회


[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [41]:
# 3행 5열의 데이터 조회
print( a[3, 5] )
print( b[3][5] )


23
23


In [42]:
# 2~4행(4행 포함), 1~3열(3열 포함) 데이터 조회
a[2:5, 1:4]

array([[13, 14, 15],
       [19, 20, 21]])