In [72]:
import numpy as np

In [73]:
l = [1, 2, 3]
x = np.array(l)
x2 = np.array([1, 2, 3], dtype='f')
x3 = np.array([1, 2, 3], dtype=np.int16)

print( type(l), type(x) )
print( x.dtype, x2.dtype, x3.dtype )

<class 'list'> <class 'numpy.ndarray'>
int64 float32 int16


In [74]:
a=np.array([1,2,3])
print (a, a.ndim)

a = np.array([[1, 2], [3, 4]])
print (a, a.ndim)

[1 2 3] 1
[[1 2]
 [3 4]] 2


In [75]:
a=np.array([1, 2, 3, 4, 5])
print (a, a.ndim)

a=np.array([1, 2, 3, 4, 5], ndmin=2)
print (a, a.ndim)


[1 2 3 4 5] 1
[[1 2 3 4 5]] 2


In [76]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print (a.shape) 

a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a) 
print(a.shape) 

a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)
print(b.shape, a.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2) (2, 3)


In [77]:
# a = np.array(range(24))
a = np.arange(24) # np.arange : 0 ~ 23까지 정수로 ndarray 만들기
print(a.ndim)
b = a.reshape(2,4,3)
print(b.ndim)
print(b)


1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [78]:
x = np.empty([3,2])
print(x)

x = np.zeros((3,2))
print(x)

x = np.ones([3,2])
print(x)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [79]:
x = np.arange(10,21,2)
print (x)

[10 12 14 16 18 20]


In [80]:
x = np.linspace(1,2,5, retstep = True)
print (x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [81]:
a = np.arange(10)
b1 = a[2:7]
b2 = a[2:7:2]
print(a)
print(b1)
print(b2)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [82]:
a = np.arange(10)
b = a[5]
print(a)
print (b)

[0 1 2 3 4 5 6 7 8 9]
5


In [83]:
a = np.arange(24)
a = a.reshape((4,6))
b = a.tolist() # ndarray -> list 변환

print(a)
b

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [84]:
print( a[1:] )
print( b[1:] )

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


In [85]:
# 0행과 2행 데이터 조회
print(a[ [0, 2] ]) # 인덱싱을 리스트, 튜플, ndarray 등으로 수행
print([b[0], b[2]])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[0, 1, 2, 3, 4, 5], [12, 13, 14, 15, 16, 17]]


In [86]:
# 3열 데이터 조회
print( a[:,3] ) # ndarray의 2차원 인덱싱, 슬라이싱 -> ar[row-indexing, col-indexing], ar[row-slicing, col-slicing]
print( [ v[3] for v in b ] )


[ 3  9 15 21]
[3, 9, 15, 21]


In [87]:
print( a[:, [2, 5]]) # 모든 행의 2열, 5열 데이터 조회

[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]


In [88]:
print(a[[1, 3], :]) # 1, 3행의 모든 열 데이터 조회


[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [89]:
# 3행 5열의 데이터 조회
print( a[3, 5] )
print( b[3][5] )


23
23


In [90]:
# 2~4행(4행 포함), 1~3열(3열 포함) 데이터 조회
a[2:5, 1:4]

array([[13, 14, 15],
       [19, 20, 21]])

In [91]:
# boolean indexing
print(a)

# print( a[ [True, False, True, True] ] )
print( a[ [True, False, True, True], : ] )

print( a[:, [True, True, False, False, True, False]])
# print( a[:, [True, True, False, False, True]]) # 오류 : boolean 리스트와 행 또는 열의 갯수는 일치해야 합니다.

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  4]
 [ 6  7 10]
 [12 13 16]
 [18 19 22]]


In [92]:
# boolean indexing
print(a)

print( a[:, 4] >= 10 ) # 4열의 값이 10 이상인지 여부
# print( b[0] > 3) 리스트와 단일 값 연산 불가능

# 4열의 값이 10 이상인 행 조회
# a[ a[:, 4] >= 10 ]
mask = a[:, 4] >= 10
a[ mask ]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[False  True  True  True]


array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [93]:
a1 = np.array([True, False, True])
b1 = np.array([True, False, False])

print(True and True)
print(True and False)
print(True or False)

# print( a1 and b1 ) # 오류 : and / or는 단일 값에 논리 연산
print( a1 & b1 ) # ndarray의 각 값에 대한 논리 연산은 &, |

True
False
True
[ True False False]


In [95]:
# 전체 데이터를 대상으로 짝수만 조회
print(a)
mask1 = a % 2 == 0
mask2 = a > 0
# print(mask1)
# print(mask2)
mask3 = mask1 & mask2
# print(mask3)
a[mask3]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a + b # 두 ndarray를 더하면 요소별 연산 수행
print(c) 
print([1, 2, 3, 4] + [10, 20, 30, 40]) # 두 리스트를 더하면 리스트 결합

a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print (a + b)



[11 22 33 44]
[1, 2, 3, 4, 10, 20, 30, 40]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
